services:
  - docker
before_install:
  - docker build -t sangam156/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sangam156/react-test npm test

after_success:
  - docker build -t sangam156/muli-client ./client
  - docker build -t sangam156/multi-nginx ./nginx
  - docker build -t sangam156/multi-server ./server
  - docker build -t sangam156/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sangam156/muli-client
  - docker push sangam156/multi-nginx
  - docker push sangam156/multi-server
  - docker push sangam156/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-720777169255
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

